-- Additive, repeatable. Run after 001, against each destination's own database.
CREATE TABLE IF NOT EXISTS takp_bot_runtime (
 bot_id INT UNSIGNED NOT NULL PRIMARY KEY,
 active TINYINT UNSIGNED NOT NULL DEFAULT 0,
 hp INT NOT NULL DEFAULT -1,
 mana INT NOT NULL DEFAULT -1,
 generation INT UNSIGNED NOT NULL DEFAULT 0,
 stance TINYINT UNSIGNED NOT NULL DEFAULT 1,
 saved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS takp_bot_inventory (
 bot_id INT UNSIGNED NOT NULL,
 slot SMALLINT UNSIGNED NOT NULL,
 item_id INT UNSIGNED NOT NULL,
 charges SMALLINT UNSIGNED NOT NULL,
 PRIMARY KEY(bot_id,slot)
) ENGINE=InnoDB;
INSERT IGNORE INTO takp_bot_schema(version) VALUES(2);
